### ISSUE TITLE
Setup unit tests, code coverage integrate them with Travis CI

### ISSUE THREAD

**Issue by kabirbaidhya** [kabirbaidhya/get-js#13]
Setup unit tests, code coverage and Travis CI Integration. 

**Requirements**
 - Preferred Tools
   - mocha, chai for tests and assertions
 - Add few tests.

**Comment by beinganonymous** [comment]
@kabirbaidhya can i take over this ?

**Comment by kabirbaidhya** [comment]
Sure, @beinganonymous you can. Thanks :).

**Comment by kabirbaidhya** [comment]
This issue is still open yet.
