### ISSUE TITLE
Adds angular as a dependency

### ISSUE THREAD

**Issue by pavermakov** [kabirbaidhya/get-js#4]
<img width="287" alt="screen shot 2018-03-17 at 00 11 24" src="https://user-images.githubusercontent.com/10779996/37544905-c105d736-2977-11e8-8744-6ae4aa1b20d4.png">

What the heck? I thought this was a standalone package.

**Comment by kabirbaidhya** [comment]
@pavermakov Fixed in the latest release [0.0.5](https://github.com/kabirbaidhya/get-js/releases/tag/v0.0.5).
